import { FaAws, FaJava, FaLinux, FaPython, FaShieldAlt } from "react-icons/fa";
import { SiAnsible, SiCoursera, SiCplusplus, SiGithub, SiGoogle, SiGooglecloud, SiJest, SiLaravel, SiPhp, SiRecoil, SiRedux, SiRust, SiSalesforce, SiUdemy, SiWordpress } from "react-icons/si";

import { FaReact, FaNodeJs, FaHtml5, FaCss3Alt, FaGitAlt } from "react-icons/fa";
import { SiNextdotjs, SiTypescript, SiTailwindcss, SiJavascript, SiFramer, SiNestjs, SiExpress, SiPostgresql, SiMongodb, SiDocker, SiKubernetes, SiRedis, SiApachekafka } from "react-icons/si";

export type ProjectTag = "All" | "Full Stack" | "Frontend" | "Backend" | "DevOps" | "Open Source";

export const projectsData = [
    {
        id: 1,
        title: "DevLink Hub",
        description: "A full-stack developer collaboration platform where engineers can discover open-source projects, form teams, and manage contribution workflows with real-time notifications.",
        longDescription: "Built with Next.js App Router and NestJS microservices. Features OAuth2, real-time WebSocket notifications, GitHub integration, and a PostgreSQL + Redis stack.",
        tags: ["Full Stack", "Open Source"] as ProjectTag[],
        tech: ["Next.js", "NestJS", "PostgreSQL", "Redis", "Docker"],
        github: "https://github.com/anugrahthomas",
        live: "https://github.com/anugrahthomas",
        gradient: "from-violet-600 via-purple-600 to-indigo-600",
        glowColor: "rgba(139,92,246,0.3)",
        featured: true,
        status: "Live",
    },
    {
        id: 2,
        title: "CloudMetrics",
        description: "A real-time infrastructure observability dashboard for AWS and GCP resources, with anomaly detection, cost tracking, and Slack alerting.",
        longDescription: "Serverless architecture using AWS Lambda, EventBridge, and Timestream. Frontend built with Next.js and Recharts for rich data visualisation.",
        tags: ["Full Stack", "DevOps"] as ProjectTag[],
        tech: ["Next.js", "AWS Lambda", "Timestream", "TypeScript", "Tailwind CSS"],
        github: "https://github.com/anugrahthomas",
        live: "https://github.com/anugrahthomas",
        gradient: "from-orange-500 via-amber-500 to-yellow-500",
        glowColor: "rgba(249,115,22,0.3)",
        featured: true,
        status: "Live",
    },
    {
        id: 3,
        title: "SnapStore",
        description: "A high-performance e-commerce storefront with server components, ISR, cart persistence, Stripe checkout, and a headless CMS for product management.",
        longDescription: "Leverages Next.js 14 App Router with React Server Components, Stripe Elements, Sanity CMS, and Vercel Edge Functions for peak performance.",
        tags: ["Full Stack", "Frontend"] as ProjectTag[],
        tech: ["Next.js", "TypeScript", "Stripe", "Sanity", "Tailwind CSS"],
        github: "https://github.com/anugrahthomas",
        live: "https://github.com/anugrahthomas",
        gradient: "from-emerald-500 via-teal-500 to-cyan-500",
        glowColor: "rgba(16,185,129,0.3)",
        featured: false,
        status: "Live",
    },
    {
        id: 4,
        title: "TaskFlow API",
        description: "A RESTful task management API with JWT auth, role-based access control, audit logs, and WebSocket support for live board updates.",
        longDescription: "NestJS monolith with PostgreSQL, TypeORM, Bull queue for background jobs, and full Swagger docs. Deployed on GCP Cloud Run via Docker.",
        tags: ["Backend"] as ProjectTag[],
        tech: ["NestJS", "PostgreSQL", "Docker", "TypeScript", "Redis"],
        github: "https://github.com/anugrahthomas",
        live: null,
        gradient: "from-rose-500 via-pink-500 to-fuchsia-500",
        glowColor: "rgba(244,63,94,0.3)",
        featured: false,
        status: "In Progress",
    },
    {
        id: 5,
        title: "PortfolioKit",
        description: "An open-source portfolio starter template with dark mode, Framer Motion animations, MDX blog support, and one-click Vercel deployment.",
        longDescription: "Built with Next.js, Tailwind CSS, and MDX. Includes a blog engine, project showcase, contact form, and full SEO setup out of the box.",
        tags: ["Frontend", "Open Source"] as ProjectTag[],
        tech: ["Next.js", "Tailwind CSS", "Framer Motion", "MDX", "TypeScript"],
        github: "https://github.com/anugrahthomas",
        live: "https://github.com/anugrahthomas",
        gradient: "from-sky-500 via-blue-500 to-indigo-500",
        glowColor: "rgba(14,165,233,0.3)",
        featured: true,
        status: "Live",
    },
    {
        id: 6,
        title: "K8s Cost Optimizer",
        description: "A CLI + dashboard tool that analyzes Kubernetes cluster resource usage, identifies over-provisioned pods, and generates cost-saving recommendations.",
        longDescription: "Go-based CLI that talks to the Kubernetes API server, paired with a React dashboard. Supports multi-cluster environments and exports reports as PDF.",
        tags: ["DevOps", "Open Source"] as ProjectTag[],
        tech: ["Kubernetes", "Docker", "React", "TypeScript", "Go"],
        github: "https://github.com/anugrahthomas",
        live: null,
        gradient: "from-cyan-500 via-teal-500 to-green-500",
        glowColor: "rgba(6,182,212,0.3)",
        featured: false,
        status: "In Progress",
    },
];

export const logo = "Anugrah Thomas"

export type JourneyType = "Full-time" | "Internship" | "Freelance" | "Contract" | "Open Source";

export const journeyData = [
    {
        id: 1,
        role: "Senior Full Stack Engineer",
        company: "TechNova Labs",
        type: "Full-time" as JourneyType,
        location: "Remote",
        duration: "Jan 2024 – Present",
        current: true,
        description:
            "Leading development of a cloud-native SaaS platform serving 50k+ users. Architected a microservices migration from a monolith, reducing deployment time by 60%. Mentoring a team of 4 junior engineers.",
        highlights: ["Next.js", "NestJS", "PostgreSQL", "Kubernetes", "AWS"],
        color: "from-violet-500 to-indigo-600",
        iconColor: "text-violet-400",
        borderColor: "border-violet-500/25",
        dotColor: "bg-violet-500",
        accentBg: "bg-violet-500/10",
    },
    {
        id: 2,
        role: "Full Stack Developer",
        company: "BuildFast Agency",
        type: "Full-time" as JourneyType,
        location: "Bangalore, India",
        duration: "Jun 2022 – Dec 2023",
        current: false,
        description:
            "Delivered 12+ client projects end-to-end including e-commerce stores, SaaS dashboards, and REST APIs. Owned CI/CD pipelines and DevOps infrastructure. Reduced client onboarding time by 40%.",
        highlights: ["React", "Node.js", "MongoDB", "Docker", "Tailwind CSS"],
        color: "from-sky-500 to-blue-600",
        iconColor: "text-sky-400",
        borderColor: "border-sky-500/25",
        dotColor: "bg-sky-500",
        accentBg: "bg-sky-500/10",
    },
    {
        id: 3,
        role: "Frontend Engineer Intern",
        company: "Fintech Startup (YC W22)",
        type: "Internship" as JourneyType,
        location: "Remote",
        duration: "Jan 2022 – May 2022",
        current: false,
        description:
            "Built responsive UI components for a payments dashboard used by 5,000+ SMBs. Introduced Storybook for component documentation and improved Lighthouse score from 62 to 94.",
        highlights: ["React", "TypeScript", "Tailwind CSS", "Storybook", "Figma"],
        color: "from-emerald-500 to-teal-600",
        iconColor: "text-emerald-400",
        borderColor: "border-emerald-500/25",
        dotColor: "bg-emerald-500",
        accentBg: "bg-emerald-500/10",
    },
    {
        id: 4,
        role: "Open Source Contributor",
        company: "Various Projects",
        type: "Open Source" as JourneyType,
        location: "Remote",
        duration: "2021 – Present",
        current: false,
        description:
            "Active contributor to projects including Next.js ecosystem tools, UI component libraries, and developer tooling. 40+ merged PRs across 8 repositories. Maintained two personal open-source packages.",
        highlights: ["GitHub", "TypeScript", "React", "Documentation", "OSS"],
        color: "from-orange-500 to-rose-500",
        iconColor: "text-orange-400",
        borderColor: "border-orange-500/25",
        dotColor: "bg-orange-500",
        accentBg: "bg-orange-500/10",
    },
];


export const links = {
    github: "https://github.com/anugrahthomas",
    linkedin: "https://www.linkedin.com/in/devanugrahthomas",
    email: "anugrah.codes@gmail.com",
    twitter: "https://x.com/_anugrahthomas",
    instagram: "https://instagram.com/_anugrahthomas",
}

export const navLinks = [{
    title: "About",
    link: "/#about"
}, {
    title: "Projects",
    link: "/#projects"
}, {
    title: "Skills",
    link: "/#skills"
}, {
    title: "Experience",
    link: "/#journey"
}, {
    title: "Contact",
    link: "/#contact"
}]

export const certifications = [
    {
        id: 1,
        title: "Generative AI Apps & Solutions",
        issuer: "Udemy",
        date: "Aug 2025",
        description: "Learned to build generative AI applications using no-code tools, covering prompt design, automation, and practical AI solutions.",
        icon: SiUdemy,
        iconColor: "#A435F0",
        gradient: "from-purple-500/20 to-pink-500/20",
        border: "border-purple-500/30",
        badge: "Udemy",
        link: "https://www.udemy.com/certificate/UC-5e5996cc-6274-48ff-a34a-3d49314c5095/",
    },
    {
        id: 2,
        title: "Ethical Hacking",
        issuer: "Code Sprint",
        date: "Mar 2024",
        description: "Completed 30+ hours of training on ethical hacking, covering network security, penetration testing, vulnerabilities, and cybersecurity best practices.",
        icon: FaShieldAlt,
        iconColor: "#35609C",
        gradient: "from-gray-500/20 to-slate-600/20",
        border: "border-gray-500/30",
        badge: "eth",
        link: "https://drive.google.com/file/d/1unnKfX_qgu6Wgz3QvvIs3sQhVJ7a6_-8/view?usp=sharing",
    },
    {
        id: 3,
        title: "Cloud Computing",
        issuer: "NPTEL (IIT Kharagpur)",
        date: "Oct 2025",
        description: "Completed a course on cloud computing covering virtualization, cloud architecture, deployment models, and basic cloud services.",
        icon: SiGooglecloud,
        iconColor: "#4285F4",
        gradient: "from-blue-500/20 to-sky-500/20",
        border: "border-blue-500/30",
        badge: "NPTEL",
        link: "https://drive.google.com/file/d/1_mJHMqs3qLWv6CB5eO7iFYBSp45Lachs/view?usp=sharing",
    },
    {
        id: 4,
        title: "Computer Hardware & Operating Systems",
        issuer: "IBM",
        date: "Sept 2024",
        description: "Learned fundamentals of computer hardware, operating systems, system components, and basic troubleshooting techniques.",
        icon: SiCoursera,
        iconColor: "#FF9900",
        gradient: "from-orange-500/20 to-amber-500/20",
        border: "border-orange-500/30",
        badge: "IBM",
        link: "https://www.coursera.org/verify/ZGLCAIT56CO1",
    },
    {
        id: 5,
        title: "The Bits and Bytes of Computer Networking",
        issuer: "Google",
        date: "Sep 2024",
        description: "Learned fundamentals of computer networking, including TCP/IP, DNS, HTTP, network models, and troubleshooting connectivity issues.",
        icon: SiGoogle,
        iconColor: "#0081FB",
        gradient: "from-indigo-500/20 to-purple-500/20",
        border: "border-indigo-500/30",
        badge: "Google",
        link: "https://www.coursera.org/verify/IB1XDLF8ZVAT",
    },
    {
        id: 6,
        title: "Advanced JavaScript & OOP",
        issuer: "Eduonix",
        date: "Sept 2023",
        description: "Learned advanced JavaScript concepts including ES6+, asynchronous programming, and object-oriented programming principles.",
        icon: SiJavascript,
        iconColor: "#00A4EF",
        gradient: "from-cyan-500/20 to-blue-500/20",
        border: "border-cyan-500/30",
        badge: "Javascript",
        link: "https://www.eduonix.com/certificate/6408932e5f",
    },
    {
        id: 7,
        title: "Interpersonal Communication for Engineering Leaders",
        issuer: "Rice University",
        date: "Mar 2026",
        description: "Learned effective communication, teamwork, leadership skills, and strategies for professional interactions in engineering environments.",
        icon: SiCoursera,
        iconColor: "#10A37F",
        gradient: "from-emerald-500/20 to-teal-500/20",
        border: "border-emerald-500/30",
        badge: "Communication",
        link: "https://www.coursera.org/verify/92O0JL0KR7LU",
    },
];

export const educationData = [
    {
        id: 1,
        degree: "Bachelor of Technology",
        field: "Computer Science & Engineering",
        institution: "Lovely Professional University",
        location: "Jalandhar, Punjab",
        duration: "2023 - 2027",
        grade: "8.0 CGPA",
        description:
            "Studied core computer science fundamentals including Data Structures, Algorithms, Operating Systems, Database Management, and Software Engineering. Participated in hackathons and part of college tech club.",
        highlights: ["DSA", "OS", "CN", "DBMS", "Software Engineering", "Web Dev"],
        color: "from-sky-500 to-blue-600",
        iconColor: "text-sky-500",
        borderColor: "border-sky-500/30",
        dotColor: "bg-sky-500",
    },
    {
        id: 2,
        degree: "Diploma",
        field: "RAC Electrical (Refrigeration & Air Conditioning)",
        institution: "Skill & Entrepreneurship Institute",
        location: "Roorkee, Uttarakhand",
        duration: "2022 - 2023",
        grade: "90%",
        description:
            "Strong foundation in electrical and cooling systems, with knowledge of thermodynamics, pressure, and refrigerant gases like CH2F2. Experienced in wiring, installation, and troubleshooting.",
        highlights: ["Thermodynamics & Heat Transfer",
            "Pressure Systems",
            "Electrical Wiring",
            "Troubleshooting",
            "Safety Practices"],
        color: "from-orange-500 to-orange-600",
        iconColor: "text-orange-500",
        borderColor: "border-orange-500/30",
        dotColor: "bg-orange-500",
    },
    {
        id: 3,
        degree: "Higher Secondary Certificate",
        field: "Science (Physics, Chemistry, Mathematics)",
        institution: "S. R. Public School",
        location: "Saharanpur, Uttar Pradesh",
        duration: "2021 – 2022",
        grade: "88.2%",
        description:
            "Focused on core sciences with Mathematics as electives. Secured a campus-level rank in the board examinations.",
        highlights: ["Mathematics", "Physics", "Chemistry"],
        color: "from-violet-500 to-purple-600",
        iconColor: "text-violet-500",
        borderColor: "border-violet-500/30",
        dotColor: "bg-violet-500",
    },
    {
        id: 4,
        degree: "Secondary School Certificate",
        field: "General Education",
        institution: "S. R. Public School",
        location: "Saharanpur, Uttar Pradesh",
        duration: "2019 - 2020",
        grade: "72.8%",
        description:
            "Strong academic foundation with early interest in Mathematics and Technology. Active in extracurriculars including quiz competitions and science fairs.",
        highlights: ["Mathematics", "Science", "Technology"],
        color: "from-emerald-500 to-teal-600",
        iconColor: "text-emerald-500",
        borderColor: "border-emerald-500/30",
        dotColor: "bg-emerald-500",
    },
];

export const skillsData = [
    { name: "React", Icon: FaReact, color: "#61DAFB" },
    { name: "Next.js", Icon: SiNextdotjs, color: "#000000" },
    { name: "TypeScript", Icon: SiTypescript, color: "#3178C6" },
    { name: "Tailwind CSS", Icon: SiTailwindcss, color: "#06B6D4" },
    { name: "JavaScript", Icon: SiJavascript, color: "#F7DF1E" },
    { name: "Node.js", Icon: FaNodeJs, color: "#339933" },
    { name: "HTML5", Icon: FaHtml5, color: "#E34F26" },
    { name: "CSS3", Icon: FaCss3Alt, color: "#1572B6" },
    { name: "Git", Icon: FaGitAlt, color: "#F05032" },
    { name: "GitHub", Icon: SiGithub, color: "#909090ff" },
    { name: "Framer Motion", Icon: SiFramer, color: "#0055FF" },
    { name: "NestJS", Icon: SiNestjs, color: "#E0234E" },
    { name: "Express.js", Icon: SiExpress, color: "#FFFFFF" },
    { name: "PostgreSQL", Icon: SiPostgresql, color: "#336791" },
    { name: "MongoDB", Icon: SiMongodb, color: "#47A248" },
    { name: "Docker", Icon: SiDocker, color: "#2496ED" },
    { name: "Kubernetes", Icon: SiKubernetes, color: "#326CE5" },
    { name: "Redis", Icon: SiRedis, color: "#DC382D" },
    { name: "Kafka", Icon: SiApachekafka, color: "#565656ff" },
    { name: "Redux", Icon: SiRedux, color: "#764abc" },
    { name: "Recoil", Icon: SiRecoil, color: "#0055FF" },
    { name: "AWS", Icon: FaAws, color: "#FF9900" },
    { name: "C++", Icon: SiCplusplus, color: "#2168f6ff" },
    { name: "Java", Icon: FaJava, color: "#FF9900" },
    { name: "Php", Icon: SiPhp, color: "#777bb4ff" },
    { name: "Python", Icon: FaPython, color: "#FFD43B" },
    { name: "Rust", Icon: SiRust, color: "#FF6C3D" },
    { name: "Jest", Icon: SiJest, color: "#99425B" },
    { name: "Ansible", Icon: SiAnsible, color: "#00b78cff" },
    { name: "Wordpress", Icon: SiWordpress, color: "#1d85d4ff" },
    { name: "Linux", Icon: FaLinux, color: "#acacacff" },
    { name: "Laravel", Icon: SiLaravel, color: "#ff2d20ff" },
    { name: "SalesForce", Icon: SiSalesforce, color: "#00a3d9ff" },
];